# During the github workflow to auto deploy the app
# This config file will be used to overwrite the config.yml in the schematic folder
#
# Please modify the configuration values based on your project

# Do not change the 'definitions' section unless you know what you're doing
definitions:
  synapse_config: '.synapseConfig'
  creds_path: 'credentials.json' # google oauth client
  token_pickle: 'token.pickle' # google oauth client
  service_acct_creds: 'schematic_service.json' # google service key
  manifest_basename: 'synapse_storage_manifest'
  manifest_folder: 'manifests' # manifests will be downloaded to this folder
  # token_creds: 'syn28152053' # syn23643259 synapse ID of credentials.json file

manifest:
  # if making many manifests, just include name prefix
  title: 'GF'  
  data_type:
    - 'GF'
  # - title: Core Clinical Data
  #   data_type: ClinicalCore
  # - title: Breast Cancer Clinical Data
  #   data_type: BreastCancerTier3
  # - title: Ovarian Cancer Clinical Data
  #   data_type: OvarianCancerTier3
  # - title: Imaging Level 2
  #   data_type: ImagingLevel2
  # - title: Imaging Level 3
  #   data_type: ImagingLevel3
  # - title: Other Assay
  #   data_type: OtherAssay

model:
  input:
    download_url: 'https://raw.githubusercontent.com/gf-dcc/data-model/main/GF.jsonld'
    repo: 'gf-dcc/data-models'
    location: 'data-models/GF.jsonld'
    file_type: 'local'

style:
  google_manifest:
    req_bg_color:
      red: 0.9215
      green: 0.9725
      blue: 0.9803
    opt_bg_color:
      red: 1.0
      green: 1.0
      blue: 0.9019
    master_template_id: '1LYS5qE4nV9jzcYw5sXwCza25slDfRA1CIg3cs-hCdpU'
    strict_validation: true
