# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: shiny-deploy-dev

on:
  push:
    branches:
      - gf-dev
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '**/*.md'
      - '**/.gitignore'

jobs:
  # TO-DO: Add test job
  
  shiny-deploy:
    runs-on: ubuntu-latest
    environment: development
    container: rocker/rstudio:4.1.2
    env:
      # This should not be necessary for installing from public repo's however remotes::install_github() fails without it.
      GITHUB_PAT: ${{ secrets.REPO_PAT }}

    steps:
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pip python3.8-venv libcurl4-openssl-dev

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Create and Activate Python Virtual Environment
        shell: bash
        run: |
          python3 -m venv .venv
          chmod 755 .venv/bin/activate
          source .venv/bin/activate

      - name: Install R Packages Dependencies
        run: |
          R -f install-pkgs.R

      - name: Install Schematic
        shell: bash
        run: |
          # has to activate each bash step
          source .venv/bin/activate
          # use 'poetry' to install schematic from the develop branch 
          pip3 install poetry
          git clone --single-branch --branch dev-gf https://github.com/gf-dcc/schematic.git
          cd schematic
          poetry build
          pip3 install dist/schematicpy-1.0.0-py3-none-any.whl

      - name: Set Configurations for Schematic
        shell: bash
        run: |
          source .venv/bin/activate
          # download data model to the correct location
          R -e '
            config <- yaml::yaml.load_file("schematic_config.yml");
            url  <- config$model$input$download_url;
            path <- config$model$input$location;
            system(sprintf("mkdir -p %s", dirname(path)));
            system(sprintf("wget %s -O %s", url, path));
          '
          # write out configuration files using github secrets
          echo "${{ secrets.SCHEMATIC_SERVICE_ACCT_CREDS }}" > schematic_service.json

      - name: zip virtual env
        shell: bash
        # ShinyApps has a limit of 7000 files, far exceeded by the many Python dependencies
        # that this app' has.  As a workaround we zip the virtual environment and later
        # unzip it in 'global.R'
        run: |
          zip -rm .venv.zip .venv

      - name: Authorize and deploy app
        shell: Rscript {0}
        run: |
          appName <- "gf-data-curator-dev"
          
          rsConnectUser <- "${{ secrets.RSCONNECT_USER }}"
          rsConnectToken <- "${{ secrets.RSCONNECT_TOKEN }}"
          rsConnectSecret <- "${{ secrets.RSCONNECT_SECRET }}"

          # create config file
          config <- "CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}"
          config <- c(config, "CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}")
          appUrl <- sprintf("https://%s.shinyapps.io/%s", rsConnectUser, appName)
          config <- c(config, sprintf("APP_URL: %s", appUrl))

          configFileConn <- file("oauth_config.yml")
          tryCatch(
            writeLines(config, configFileConn),
            finally=close(configFileConn)
          )
          rsconnect::setAccountInfo(rsConnectUser, rsConnectToken, rsConnectSecret)
          rsconnect::deployApp(appName = appName)
